Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: dm-
    SupplierDeployMetadata:
      AcrImageArtifactRelation:
        '{{ computenest::acrimage::demo }}':
          ArtifactId: artifact-58a1ffbe260e490dbc52
    TemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'docs/architecture.png'
        AllowedRegions:
          - cn-hangzhou
  ServiceType: private
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: ECS单机版
        Operation:
          - Name: 变配ECS实例规格
            Description: 变配ECS实例规格
            Type: Custom
            SupportPredefinedParameters: false
            EnableLogging: false
            Parameters:
              - EcsInstanceType
  UpgradeMetadata:
    Description: 升级
    SupportRollback: true
    SupportUpgradeFromVersions: [ ]
    UpgradeComponents:
      - Configuration
      - Resource
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: spring boot demo
    Image: 'resources/icons/service_logo.png'
    Name: SpringBoot单机版(docker版)
  ShareType: Public
  ApprovalType: Manual
AcrImageBuilder:
  AcrImage_1:
    DockerFilePath: '.computenest/resources/artifact_resources/acr_image/Dockerfile'
    RepoName: spring-boot-demo
    Tag: v1.0

